package com.javamultiplex.projecteuler;

import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

public class Problem29 {

	public static void main(String[] args) {
		
		int a,b,limit=100;
		Set<BigInteger> powers=new HashSet<>();
		BigInteger temp=BigInteger.ZERO;
		BigInteger a1=BigInteger.ZERO;
		int size=0;
		for(a=2;a<=limit;a++)
		{
			for(b=2;b<=limit;b++)
			{
				//Converting int to String and assign to BigInteger.
				a1=new BigInteger(String.valueOf(a));
				temp=a1.pow(b);
				powers.add(temp);
				
			}
		}
		size=powers.size();
		System.out.println("Distinct terms in the sequence generated by a^b for 2 <= a <= 100 and 2 <= b <= 100 are : "+size);
	}
	
}
